image: golang:latest

types:
  - test

before_script:
 - apt-get -qq update && apt-get -qy install git-core; go get -d -t

test:
  type: test
  tags: ["docker"]
  script:
    - go test -v
  only:
    - master
