language: go

env:
  matrix:
    - GO_TAGS=libc
    - GO_TAGS=ldap
go:
  - "1.10"
  - "1.11"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

script: 
  - go test -tags $GO_TAGS -coverprofile c.out -v .
